name: Build Android APK Success Final
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm init -y
          npm install --force @capacitor/core @capacitor/cli @capacitor/android @capacitor/push-notifications
          mkdir -p www

      - name: Build Android Structure
        run: |
          npx cap add android || echo "Exists"
          mkdir -p android/app/
          cp google-services.json android/app/
          npx cap sync android

      - name: Upgrade Android Build Tools
        # هذا السطر يحل مشكلة فشل التجميع عبر ترقية الإصدارات برمجياً
        run: |
          sed -i 's/compileSdkVersion = 30/compileSdkVersion = 33/g' android/variables.gradle
          sed -i 's/targetSdkVersion = 30/targetSdkVersion = 33/g' android/variables.gradle

      - name: Build APK Final
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Export APK
        uses: actions/upload-artifact@v4
        with:
          name: Jazmati-Final-Work
          path: android/app/build/outputs/apk/debug/app-debug.apk
 
